version: "3.7"


x-app: &app
  build: reposter
  image: reposter
  env_file:
    - .envs/prod/app.env
    - .envs/prod/db.env
  depends_on:
    - db


x-worker: &worker
  <<: *app
  depends_on:
    - db
    - redis


services:
  db:
    image: postgres:11.1
    hostname: db
    env_file:
      - .envs/prod/db.env
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis:
    image: redis:5
    hostname: redis
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data

  app:
    <<: *app
    command: ["./scripts/web.sh", "prod"]
    stop_signal: SIGINT
    ports:
      - 8000:8000

  worker:
    <<: *worker
    command: ["./scripts/celery.sh"]

  beat:
    <<: *worker
    command: ["./scripts/beat.sh"]


volumes:
  dbdata:
  redisdata:
